Complete Org Refresh implementation
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #144
Opened 2021-08-30 15:36 UTC by zzori-theoriginal

@ccheetham @dtillman The implementation for this story is complete; however, while looking into tests for this functionality, we discovered that we had not previously been testing this refresh for the Spaces, either. While trying to write a test for both Orgs and Spaces, we realized that the tests were flaky due to us using `Task` to spin off background tasks, which in turn can cause a "race" for things to be completed, causing the flaky tests. Do either of you know of a more reliable way to test this method or a way to re-write the method in order to make it easier to test?

Thanks in advance for any help y'all can provide!

2021-08-30 15:37 UTC, ccheetham requested changes
minor nit

2021-08-30 15:37 UTC, ccheetham commented on src/ViewModels/test/TasExplorerViewModelTests.cs
> +
remove this line?

2021-08-30 19:27 UTC, ccheetham approved these changes
lgtm

2021-08-31 21:02 UTC, atwoosnam approved these changes

2021-09-02 17:33 UTC, merged