Update icons
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #145
Opened 2021-08-30 19:25 UTC by zzori-theoriginal

2021-08-30 19:27 UTC, ccheetham approved these changes
lgtm

2021-08-31 15:31 UTC, atwoosnam requested changes

2021-08-31 15:31 UTC, atwoosnam commented on src/WpfViews/src/TasExplorerView.xaml
> +                    <Image Source="Resources/Refresh_16.png"
I misspelled the name of this image -- this is a self reminder to fix this typo before merging

```suggestion
                    <Image Source="Resources/Refresh_16x.png" 
```

2021-08-31 19:28 UTC, atwoosnam commented on src/WpfViews/src/TasExplorerView.xaml
> +                    <Image Source="Resources/Refresh_16.png"
Resolved by 4c4cf68

2021-08-31 19:31 UTC, atwoosnam approved these changes

2021-08-31 19:32 UTC, merged