Add logic and tests for StartCommand [#175]
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #194
Opened 2021-11-08 21:15 UTC by zzori-theoriginal

2021-11-09 14:31 UTC, ccheetham requested changes
nits

2021-11-09 14:31 UTC, ccheetham commented on src/ViewModels/src/DeploymentDialog/DeploymentDialogViewModel.cs
> +
is this blank line intended?

2021-11-09 14:31 UTC, ccheetham commented on src/WpfViews/src/DeploymentDialogView.xaml.cs
> -
need a blank line

2021-11-09 16:53 UTC, zzori-theoriginal commented on src/ViewModels/src/DeploymentDialog/DeploymentDialogViewModel.cs
> +
done

2021-11-09 16:53 UTC, zzori-theoriginal commented on src/WpfViews/src/DeploymentDialogView.xaml.cs
> -
done

2021-11-10 21:40 UTC, atwoosnam requested changes

2021-11-10 21:40 UTC, atwoosnam commented on src/ViewModels/src/DeploymentDialog/DeploymentDialogViewModel.cs
>      }
I'm thinking we might want to set StartCommand to null if it's either null or whitespace to account for:
1. if a manifest is provided with no start command (clear any previous value to sync with the new manifest)
2. if a manifest is provided with whitespace for a start command (don't keep the whitespace in the new manifest)... (is this even a real scenario though?)

```suggestion
        private void SetStartCommandFromManifest(AppManifest appManifest)
        {
            var startCmmd = appManifest.Applications[0].Command;
           
            StartCommand = string.IsNullOrWhiteSpace(startCmmd) ? null : startCmmd;
        }
    }
```

2021-11-11 16:21 UTC, atwoosnam approved these changes

2021-11-11 16:31 UTC, merged