Fix connection restoration bug
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #229
Opened 2022-01-03 17:36 UTC by atwoosnam

Connection not restored when access token irretrievable:

![persistent-connection-bug-fix](https://user-images.githubusercontent.com/22666145/147961473-fc0b8f4a-4ac2-43ba-a3c5-13b783fe3f94.gif)

2022-01-06 15:37 UTC, ccheetham requested changes

2022-01-06 15:37 UTC, ccheetham commented on src/Services/src/CloudFoundry/CloudFoundryService.cs
> +        /// True if token is accessible & appears valid.
prefer "and" over symbol

2022-01-06 15:37 UTC, ccheetham commented on src/Services/src/CloudFoundry/ICloudFoundryService.cs
> +        bool ValidateConnection();
```suggestion
        bool IsValidConnection();
```

2022-01-07 15:45 UTC, atwoosnam commented on src/Services/src/CloudFoundry/CloudFoundryService.cs
> +        /// True if token is accessible & appears valid.
Fixed in b60fa23

2022-01-07 15:45 UTC, atwoosnam commented on src/Services/src/CloudFoundry/ICloudFoundryService.cs
> +        bool ValidateConnection();
Fixed in b60fa23

2022-01-10 15:36 UTC, ccheetham approved these changes
lgtm

2022-01-10 15:43 UTC, merged