Improve refresh behavior for tree view items in TAS Explorer
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #270
Opened 2022-02-18 21:44 UTC by atwoosnam

resolves #267
- Simplify refresh strategy (consolidate 3 different ways of loading new items into 1)
- Reduce risk of UI deadlocks by replacing deprecated call to `Application.Current.Dispatcher.Invoke()`

2022-02-24 17:19 UTC, ccheetham requested changes

2022-02-24 21:08 UTC, atwoosnam commented on src/ViewModels/src/TreeViewItems/OrgViewModel.cs
> +                                if (updatedChild is SpaceViewModel space) updateChildrenTasks.Add(ThreadingService.StartBackgroundTask(space.UpdateAllChildren));
Resolved in [be2b8dc](https://github.com/vmware-tanzu/tanzu-toolkit-for-visual-studio/pull/270/commits/be2b8dc37e1b2c903164c6dfbf53bdfac7eb7879)

2022-02-24 21:08 UTC, atwoosnam commented on src/ViewModels/src/TreeViewItems/OrgViewModel.cs
> +                                        if (!spaceStillExists) removalTasks.Add(ThreadingService.RemoveItemFromCollectionOnUiThreadAsync(Children, priorSpace));
Resolved in [be2b8dc](https://github.com/vmware-tanzu/tanzu-toolkit-for-visual-studio/pull/270/commits/be2b8dc37e1b2c903164c6dfbf53bdfac7eb7879)

2022-02-25 14:45 UTC, zzori-theoriginal approved these changes
LGTM

2022-02-28 16:11 UTC, ccheetham approved these changes

2022-02-28 17:46 UTC, merged