Redesign remote debug window
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #310
Opened 2022-04-22 01:06 UTC by atwoosnam

resolves #307

2022-04-27 16:06 UTC, atwoosnam commented
This issue seems to exist on `main` already! (see #319) 
Re-opening this PR as it didn't introduce this issue

2022-04-28 12:44 UTC, ccheetham requested changes
minor formatting changes

2022-04-28 12:44 UTC, ccheetham commented on src/Services/src/Project/IProjectService.cs
> +}
missing newline

2022-04-28 16:01 UTC, ccheetham approved these changes
lgtm

2022-04-28 18:10 UTC, merged