UI improvements
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #76
Opened 2021-05-05 14:28 UTC by zzori-theoriginal

Notes:
- Didn't get rid of the close 'x' in top right corner because doing so would get rid of the entire title area and I feel like that trade of wasn't worth it
    - Also, since the title block is still there, the user can still move the window (which I know is something that we didn't want); 
    however, I got rid of the ability to resize the window
- Added the close button at the bottom of the window as requested
- Added logic for the close button functionality 

Snapshot:
![errorwindow](https://user-images.githubusercontent.com/52456455/117157320-81d24580-ad8c-11eb-8e5c-ca0bd68f834a.png)

2021-05-05 18:55 UTC, jkonicki commented
Code looks good.  

For the Dialog, it should follow the look and feel of the rest of the UI (possibly a different ticket to take a look at this).  The text box should have more whitespace around it.  Make sure the text box can scroll in the case of a large error message.  

As an example, this is more like what I would expect from the error dialog look and feel.  Note the icon near the message that shows it is an error versus a warning or informational message.
![image](https://user-images.githubusercontent.com/145382/117194027-970d9b00-adb1-11eb-92a6-7023a9d8682b.png)

2021-05-06 13:35 UTC, ccheetham requested changes

2021-05-06 13:35 UTC, ccheetham commented on WpfViews/ErrorDialogView.xaml.cs
> +            this.Close();
`this.` should be removed.

2021-05-07 16:00 UTC, dtillman approved these changes

2021-05-07 20:16 UTC, zzori-theoriginal commented on WpfViews/ErrorDialogView.xaml.cs
> +            this.Close();
this has been removed!

2021-05-10 20:24 UTC, dtillman submitted a review, later dismissed

2021-05-11 11:03 UTC, ccheetham submitted a review, later dismissed

2021-05-11 14:07 UTC, atwoosnam commented on WpfViews/WpfViews.csproj
> +    <Reference Include="GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=e7570ab207bcb616, processorArchitecture=MSIL">
Do we still need these extra references? I can't remember what you said they were needed for @zzori-theoriginal

2021-05-11 16:05 UTC, atwoosnam approved these changes

2021-05-11 16:06 UTC, merged