Set codeCoverageEnabled: True in pipelines.yml
vmware-tanzu/tanzu-toolkit-for-visual-studio pull request #80
Opened 2021-05-14 18:43 UTC by atwoosnam

2021-05-20 14:28 UTC, TimHess commented on azure-pipelines.yml
> +    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[Tanzu.*]*"'
```suggestion
    projects: **/test/*.Tests.csproj
    arguments: '--no-build --configuration $(buildConfiguration) --collect "Code coverage"'
```

Try this

2021-05-20 14:37 UTC, TimHess commented on azure-pipelines.yml
> +    projects: **/test/*.Tests.csproj
```suggestion
    projects: `**/test/*.Tests.csproj`
```

2021-05-20 14:50 UTC, TimHess commented on azure-pipelines.yml
>      solution: '**\*.sln'
```suggestion
    solution: '**\*.sln' 
    configuration: $(buildConfiguration)
```

2021-05-20 15:03 UTC, TimHess commented on azure-pipelines.yml
```suggestion
variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
```

2021-05-20 15:53 UTC, TimHess commented on azure-pipelines.yml
> +    reports: $(Build.SourcesDirectory)/tests/**/coverage.cobertura.xml
```suggestion
    arguments: '--no-build --configuration $(buildConfiguration) --collect "XPlat Code Coverage" /p:CoverletOutputFormat=cobertura'
    reports: $(Agent.TempDirectory)/**/coverage.cobertura.xml
```

2021-05-21 14:36 UTC, zzori-theoriginal submitted a review, later dismissed

2021-05-24 14:30 UTC, ccheetham requested changes
Choose one path delimiter style rather than use a mixture.

I.e., either `/` or `\`.

2021-05-25 15:22 UTC, ccheetham approved these changes
lgtm

2021-05-25 15:23 UTC, merged